<template><div><h1 id="eslint" tabindex="-1"><a class="header-anchor" href="#eslint" aria-hidden="true">#</a> eslint</h1>
<h2 id="常用的-eslint-规则" tabindex="-1"><a class="header-anchor" href="#常用的-eslint-规则" aria-hidden="true">#</a> 常用的 eslint 规则</h2>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token comment">// 0 - off; 1 - warning; 2 - error</span>
<span class="token punctuation">{</span>
	<span class="token property">"rules"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token comment">// tempalte 缩进校验 https://eslint.vuejs.org/rules/html-indent.html</span>
		<span class="token property">"vue/html-indent"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> attribute<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> baseIndent<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> closeBracket<span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span> alignAttributesVertically<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> ignores<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">,</span>

    <span class="token comment">// html 中的{{}} 两边必须有空格  https://eslint.vuejs.org/rules/mustache-interpolation-spacing.html</span>
		<span class="token property">"vue/mustache-interpolation-spacing"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token string">"always"</span> | <span class="token string">"never"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>

    <span class="token comment">// 单行属性最多 https://eslint.vuejs.org/rules/max-attributes-per-line.html</span>
		<span class="token property">"vue/max-attributes-per-line"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> singleline<span class="token operator">:</span> <span class="token number">3</span><span class="token punctuation">,</span> multiline<span class="token operator">:</span> <span class="token punctuation">{</span> max<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> allowFirstLine<span class="token operator">:</span> <span class="token boolean">false</span> <span class="token punctuation">}</span> <span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">,</span>

    <span class="token comment">// 属性排序 https://eslint.vuejs.org/rules/attributes-order.html</span>
		<span class="token property">"vue/attributes-order"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> order<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"DEFINITION"</span><span class="token punctuation">,</span> <span class="token string">"LIST_RENDERING"</span><span class="token punctuation">,</span> <span class="token string">"CONDITIONALS"</span><span class="token punctuation">,</span> <span class="token string">"RENDER_MODIFIERS"</span><span class="token punctuation">,</span> <span class="token string">"GLOBAL"</span><span class="token punctuation">,</span> <span class="token string">"UNIQUE"</span><span class="token punctuation">,</span> <span class="token string">"TWO_WAY_BINDING"</span><span class="token punctuation">,</span> <span class="token string">"OTHER_DIRECTIVES"</span><span class="token punctuation">,</span> <span class="token string">"OTHER_ATTR"</span><span class="token punctuation">,</span> <span class="token string">"EVENTS"</span><span class="token punctuation">,</span> <span class="token string">"CONTENT"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> alphabetical<span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">,</span>

    <span class="token comment">// 组件名命名规则 https://eslint.vuejs.org/rules/component-definition-name-casing.html</span>
		<span class="token property">"vue/component-definition-name-casing"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token string">"PascalCase"</span> | <span class="token string">"kebab-case"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token comment">// export default {</span>
    <span class="token comment">//   &lt;!-- ✗ BAD --></span>
    <span class="token comment">//   name: 'my-component'</span>
    <span class="token comment">// }</span>

    <span class="token comment">// 组件在 template 的使用 https://eslint.vuejs.org/rules/component-name-in-template-casing.html</span>
		<span class="token property">"vue/component-name-in-template-casing"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"error"</span><span class="token punctuation">,</span> <span class="token string">"PascalCase"</span> | <span class="token string">"kebab-case"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token property">"registeredComponentsOnly"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token property">"ignores"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token comment">// &lt;template></span>
    <span class="token comment">//   &lt;!-- ✓ GOOD --></span>
    <span class="token comment">//   &lt;CoolComponent /></span>
    <span class="token comment">//   &lt;!-- ✗ BAD --></span>
    <span class="token comment">//   &lt;cool-component /></span>
    <span class="token comment">//   &lt;coolComponent /></span>
    <span class="token comment">//   &lt;Cool-component /></span>
    <span class="token comment">// &lt;/template></span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
