name: 部署

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # choose node.js version to use
          node-version: '14'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      # run build script
      - name: Build VuePress site
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: docs/.vuepress/dist

      # # please check out the docs of the workflow for more details
      # # @see https://github.com/crazy-max/ghaction-github-pages
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     # deploy to gh-pages branch
      #     target_branch: gh-pages
      #     # deploy the default output dir of VuePress
      #     build_dir: docs/.vuepress/dist
      #   env:
      #     # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
      #     GITHUB_TOKEN: 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